# Generated by Django 5.1.6 on 2025-02-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustracking',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
