# Generated by Django 5.1.6 on 2025-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0002_statustracking_status_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('LPG Refill', 'LPG Refill'), ('New Connection', 'New Connection'), ('Maintenance', 'Maintenance'), ('Safety Check', 'Safety Check')], default='LPG Refill', max_length=50),
        ),
    ]
