# Generated by Django 5.1.6 on 2025-02-23 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0004_alter_customersupport_user_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustracking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='gas_app.booking'),
        ),
        migrations.AlterField(
            model_name='statustracking',
            name='progress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
